version: '3'

services:
  app:
    networks:
      - default
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - sqlserver
    environment:
      - DATABASE_URL=${DATABASE_URL}
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      user: sa
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
